[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pbn_37k"
version = "2.1.1"
description = "Analysing urban initiatives"
readme = "README.md"
license = { file = "LICENSE_GPLv3.0.txt" }
requires-python = ">=3.11"
dependencies = []

[tool.setuptools.packages.find]
where = ["src","lib"]

[tool.setuptools.package-data]
mylib = ["data/*","src/data/*","src/pbn_37k/data/*"]