[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pbn_37k"
version = "2.1.2"
description = "Analysing urban initiatives"
readme = "README.md"
license = { file = "LICENSE_GPLv3.0.txt" }
requires-python = ">=3.11"
dependencies = []

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["src","lib"]


[tool.setuptools.package-data]
pbn_37k = [
    "data/*.json",
    "data/*.md",
    "data/**/*.json",
    "data/**/*.md",
    "data/*.xlsx",
    "data/**/*.xlsx"
]